### ISSUE TITLE
Unhandled Exception: 'package:flutter/src/widgets/scroll_activity.dart':

### ISSUE THREAD

**Issue by maheshperi19** [joo6077/cool_dropdown#3]
I am getting below exception if "isAnimation" as false. If it is true, then working fine.

Senario : 
Click on any value, then select dropdown and select value, then click on dropdown..... causes this issue.

> [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/widgets/scroll_activity.dart': Failed assertion: line 623 pos 15: 'duration > Duration.zero': is not true.
> package:flutter/…/widgets/scroll_activity.dart:1
> #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
> #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
> #2      new DrivenScrollActivity
> package:flutter/…/widgets/scroll_activity.dart:623
> #3      ScrollPositionWithSingleContext.animateTo
> package:flutter/…/widgets/scroll_position_with_single_context.dart:181
> #4      ScrollController.animateTo
> package:flutter/…/widgets/scroll_controller.dart:154
> #5      DropdownBodyState.setScrollPosition.<anonymous closure>
> package:cool_dropdown/drop_down_body.dart:298
> <asynchronous suspension>

**Comment by maheshperi19** [comment]
I found the issue. Please check and confirm anyone. 

In drop_down_body.dart file ==> setScrollPosition(), 

 
> _scrollController.animateTo(scrollPosition,
>               duration: au.isAnimation(
>                   status: widget.isAnimation,
>                   duration: Duration(milliseconds: 300)),
>               curve: Curves.easeInOut);

Check the condition isAnimation
> if (widget.isAnimation == true) {
>           _scrollController.animateTo(scrollPosition,
>               duration: au.isAnimation(
>                   status: widget.isAnimation,
>                   duration: Duration(milliseconds: 300)),
>               curve: Curves.easeInOut);
>         }
>
